### ISSUE TITLE
Companions don't adjust their walking speed

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#10]
Companions still run if the player walks.

**Comment by catalinstoian** [comment]
ZS_FollowPC.d

func int ZS_FollowPC_Loop()
{
	PrintDebugNpc		(PD_TA_LOOP,	"ZS_FollowPC_Loop");
	PrintGlobals		(PD_MST_DETAIL);

	//-------- SC-Meister folgen ! --------
		if	C_BodyStateContains(hero, BS_WALK) // wenn SC geht, gehe ich auch (gibt sonst so lästige Ruckler: NPC läuft, steht, läuft, ...)
		{
			AI_SetWalkmode	(self,	NPC_WALK);
		}
		else if	!C_BodyStateContains(self, BS_SWIM) // nur NPC_RUN wenn NPC nicht schwimmt und hero nicht geht (sonst würde obiges nix bringen)
		{
			AI_SetWalkmode	(self,	NPC_RUN);
		};
	if (Npc_GetDistToNpc(self,hero) > HAI_DIST_FOLLOWPC)
	{
		AI_GotoNpc		(self,	hero);
	}
	else
	{
		B_SmartTurnToNpc(self,	hero);
	};
	return		LOOP_CONTINUE;
};

**Comment by szapp** [comment]
The code does not fix the issue for me:

- Hero runs: NPC runs
- Hero walks: NPC walks (when they come close to the hero to stop)
- **Hero resumes running: NPC keeps walking and does not revert to running.**

**Comment by szapp** [comment]
I fixed it here #76. With the use of `B_FollowPC_AssessSC` it works - provided the NPC sees the player. That means: If the player walks around a corner and then starts running, the NPC will remain walking until seeing the player again.
