### ISSUE TITLE
Player can pass guards in combat mode

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#11]
The player can pass gate guards just by entering combat mode.

**Comment by catalinstoian** [comment]
B_AssessFighter.d

		else //if (Npc_IsInState(self, ZS_GuardPassage))
		{
			//-------- Auf Vergabe von Infos & Missionen checken --------
			//B_CheckForImportantInfo(self,other);
			if (Npc_CheckInfo(self,1))
			{
			return;
			}
			else
			{
			};
		};

		//-------- Waffenzieher ist im Dialog --------
		if (other.aivar[AIV_INVINCIBLE] == TRUE) 
		{
			PrintDebugNpc	(PD_ZS_CHECK, "...Fighter ist im Dialog!" );				
			return;
		};

		if ((hero.aivar[AIV_GUARDPASSAGE_STATUS] == AIV_GPS_FIRSTWARN)
		||  (hero.aivar[AIV_GUARDPASSAGE_STATUS] == AIV_GPS_LASTWARN ))
		{
		return;
		};

		//-------- Check auf Fernkampfwaffe! --------
		if ( Npc_IsInFightMode(other, FMODE_FAR) )
		{
			PrintDebugNpc			(PD_ZS_CHECK, "...Fighter führt Fernkampfwaffe!");	
						
			if (Npc_GetDistToNpc(self,other) < HAI_DIST_RANGED)
			{
				PrintDebugNpc		(PD_ZS_CHECK, "...und ist in Fernkampfreichweite!");

				if (Npc_IsAiming (other, self) )
				{
					//PrintDebugNpc		(PD_ZS_CHECK, "...und zielt auf mich!");
				
					B_FullStop 			(self);
					//Npc_SendPassivePerc	(self, 	PERC_ASSESSWARN,	self,	other); 
					AI_StartState 		(self, 	ZS_AssessFighter,	0,	"");
					return;
				};
			};
    };

**Comment by szapp** [comment]
@catalinstoian What are the implications of commenting out this condition: `else //if (Npc_IsInState(self, ZS_GuardPassage))`? Will this break normal (i.e. non-guarding) NPCs? Will any NPC that has something to say no longer react to drawing a weapon?

**Comment by szapp** [comment]
@catalinstoian What is the reason for taking `Npc_CheckInfo(self, 1)` instead of `B_CheckForImportantInfo(self,other)`
