### ISSUE TITLE
Cavalorn WPs for his routine are reversed

### ISSUE THREAD

**Issue by i5sue5** [AmProsius/gothic-1-community-patch#122]
**Describe the bug**
The WPs for the routine of Cavalorn are reversed. He stands in his hut all day and goes to the outside at night.

**Expected behavior**
Cavalron now correctly sleeps in his hut at night and stands outside at daytime.

**Comment by szapp** [comment]
https://github.com/AmProsius/gothic-1-community-patch/blob/2775fbc70322594ed1d00c96717143f0c2af5af7/scriptbase/_work/Data/Scripts/Content/Story/NPC/STT_336_Cavalorn.d#L53-L57

changed to

```D
FUNC VOID Rtn_start_336 () 
 { 
     TA_Sleep        (23,00,06,30,"OW_SAWHUT_SLEEP_01"); 
     TA_StandAround  (06,30,23,00,"OW_CAVALORN_01"); 
 }; 
```
