### ISSUE TITLE
The Butcher is described as two-handed sword

### ISSUE THREAD

**Issue by i5sue5** [AmProsius/gothic-1-community-patch#125]
**Describe the bug**
The sword *Butcher* is described as a two-handed sword in the inventory.

**Expected behavior**
The sword *Butcher* is now correctly described as a one-handed sword.

**Additional context**
* German sword name: *Schlachter*
* Instance `ItMw_1H_Sword_Bastard_02`

**Comment by AmProsius** [comment]
*Possibly*

https://github.com/AmProsius/gothic-1-community-patch/blob/2775fbc70322594ed1d00c96717143f0c2af5af7/scriptbase/_work/Data/Scripts/Content/Items/Melee_Weapons.d#L1404-L1408

changed to

```d
    description         = name;
    TEXT[2]             = NAME_Damage;                  COUNT[2]    = damageTotal;
    TEXT[3]             = NAME_Str_needed;              COUNT[3]    = cond_value[2];
    TEXT[4]             = NAME_OneHanded;
    TEXT[5]             = NAME_Value;                   COUNT[5]    = value;
```

**Comment by szapp** [comment]
Similar to #41 #44 #49.
