### ISSUE TITLE
The trading menu is opened after Sharky is appointed as new fence

### ISSUE THREAD

**Issue by i5sue5** [AmProsius/gothic-1-community-patch#126]
**Describe the bug**
The dialogue option of Sharky for Fisk's quest opens the trading menu.

**Expected behavior**
Sharky's dialog option for Fisk's quest "New Fence for Fisk" no longer opens the trading menu.

**Additional context**
* German quest name: *Neuer Hehler für Fisk*
* Instance `ORG_843_Sharky_Fisk`

**Comment by AmProsius** [comment]
*Possilby*

https://github.com/AmProsius/gothic-1-community-patch/blob/2775fbc70322594ed1d00c96717143f0c2af5af7/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_ORG_843_Sharky.d#L28-L37

changed to

```d
instance  Org_843_Sharky_Fisk (C_INFO)
{
    npc             = Org_843_Sharky;
    nr              = 2;
    condition       = Org_843_Sharky_Fisk_Condition;
    information     = Org_843_Sharky_Fisk_Info;
    permanent       = 0;
    description     = "Fisk from the Old Camp is looking for a new trading partner.";
};
```

**Comment by szapp** [comment]
Similar to #30.
