### ISSUE TITLE
Horatio may lower STRENGTH

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#15]
Horatio makes the player to lose STRENGTH if the player has more than 100 STRENGTH.

**Comment by catalinstoian** [comment]
DIA_BAU_901_Horatio.d // PrintScreen text can be changed, maybe?

func void DIA_Horatio_HelpSTR_LEARN_NOW()
{
	if (other.attribute[ATR_STRENGTH]<=(100-5))
	{
		other.attribute[ATR_STRENGTH] = other.attribute[ATR_STRENGTH] + 5;
		PrintScreen	("Strength + 5", -1,-1,"FONT_OLD_20_WHITE.TGA",2);
	}
	else if (other.attribute[ATR_STRENGTH]>100)
	{
		PrintScreen	("No increase over maximum 100!", -1,-1,"FONT_OLD_20_WHITE.TGA",2);
	}
	else
 	{
		other.attribute[ATR_STRENGTH] = 100;
		PrintScreen	("Strength: 100", -1,-1,"FONT_OLD_20_WHITE.TGA",2);
	};
				
	AI_Output (self, other,"DIA_Horatio_HelpSTR_LEARN_NOW_09_00"); //If you want to hit powerfully, you need to know the right tactics. That's the first thing you learn as a smith.
	AI_Output (self, other,"DIA_Horatio_HelpSTR_LEARN_NOW_09_01"); //Learn to push your whole arm through, from the shoulder down to the wrist.
	AI_Output (self, other,"DIA_Horatio_HelpSTR_LEARN_NOW_09_02"); //The better you get at that, the more powerful the blow. You'll get the hang of it pretty quick.
};
