### ISSUE TITLE
Potion of Haste has wrong ore value

### ISSUE THREAD

**Issue by szapp** [AmProsius/gothic-1-community-patch#158]
**Describe the bug**
Potion of Haste and has the wrong ore value.

**Expected behavior**
The Potion of Haste now has the correct ore value.
*Do **not** write the specific ore values here, because the fix takes the ore values possibly modified by a mod.*

**Additional context**
This issue was split from #41. The same bug in the Potion of Velocity is addressed in #157.

The issues are split to be able to give a proper fix status if the fix succeeds for one but fails for the other of the items.

**Comment by szapp** [comment]
https://github.com/AmProsius/gothic-1-community-patch/blob/e66b303623c042ec5cfc387a1b0d4bd352605f12/scriptbase/_work/Data/Scripts/Content/Items/Potions.d#L721

changed to

```D
value 			=	Value_Haste3;	
```

**Comment by szapp** [comment]
>* Fix #157: The *Potion of Velocity* now has the correct ore value (from 100 to 150).
>* Fix #158: The *Potion of Haste* now has the correct ore value (from 100 to 200).

You might have missed that note when updating the changelog.

> _Do **not** write the specific ore values here, because the fix takes the ore values possibly modified by a mod._

That's why the original entries I had were

> * Fix #157: The Potion of Velocity now has the correct ore value.
> * Fix #158: The Potion of Haste now has the correct ore value.

**Comment by AmProsius** [comment]
> You might have missed that note when updating the changelog.

Yep, missed it. Sorry!
