### ISSUE TITLE
Thorus' bribe dialog doesn't disappear

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#16]
Thorus can be bribed if the player has already obtained the permit to an audience with Gomez.
The option to bribe Thorus stays open after the player has already bribed him.

**Comment by catalinstoian** [comment]
DIA_GRD_200_Thorus.d

// ************************************************************
// 						Give1000Ore					
// ************************************************************
var int thorus_bribed;

INSTANCE Info_Thorus_Give1000Ore (C_INFO)
{
	npc			= GRD_200_THORUS;
	nr			= 1;
	condition	= Info_Thorus_Give1000Ore_Condition;
	information	= Info_Thorus_Give1000Ore_Info;
	permanent	= 1;
	description = "I have the 1000 nuggets of ore. Now let me go in!";
};                       

FUNC INT Info_Thorus_Give1000Ore_Condition()
{	
	if (Npc_KnowsInfo(hero,Info_Thorus_BribeGuard) && (Diego_GomezAudience == FALSE) && (thorus_bribed == FALSE))
	{
		return 1;
	};
};

FUNC VOID Info_Thorus_Give1000Ore_Info()
{
	AI_Output (other, self,"Info_Thorus_Give1000Ore_15_00"); //I have the 1000 nuggets of ore. Now let me go in!
	
	if (Npc_HasItems(other, ItMiNugget)>=1000)
	{
		B_GiveInvItems 	(other,self,ItMiNugget,1000);		
		AI_Output (self, other,"Info_Thorus_Give1000Ore_09_01"); //Alright, go ahead. You can go in the castle, but don't do anything stupid, okay?
		var C_NPC wache212; wache212 = Hlp_GetNpc(Grd_212_Torwache);
		var C_NPC wache213; wache213 = Hlp_GetNpc(Grd_213_Torwache);
		wache212.aivar[AIV_PASSGATE] = TRUE;
		wache213.aivar[AIV_PASSGATE] = TRUE;
		thorus_bribed = TRUE;
	}
	else
	{
		AI_Output (self, other,"Info_Thorus_Give1000Ore_09_02"); //Don't try'n trick me, kid. You don't have 1000 nuggets of ore!
	};
};

// ************************************************************
// 					Brief für Magier
// ************************************************************

INSTANCE Info_Thorus_LetterForMages (C_INFO)
{
	npc			= GRD_200_THORUS;
	nr			= 1;
	condition	= Info_Thorus_LetterForMages_Condition;
	information	= Info_Thorus_LetterForMages_Info;
	permanent	= 1;
	description = "I need to get into the castle! I have a letter here for the High Mage.";
};                       

FUNC INT Info_Thorus_LetterForMages_Condition()
{	
	if	Npc_KnowsInfo(hero, Info_Thorus_EnterCastle) && (Diego_GomezAudience == FALSE) && (thorus_bribed == FALSE)
	&&	(Npc_HasItems (hero, ItWr_Fire_Letter_01) || Npc_HasItems (hero, ItWr_Fire_Letter_02))
	{
		return 1;
	};
};

**Comment by szapp** [comment]
It is quite tricky to set the variable `thorus_bribed`. Do you think it is enough to check if the AI-variable `AIV_PASSGATE` of `Grd_213_Torwache` is set to TRUE, i.e. the hero is allow to enter the castle?

**Comment by AmProsius** [comment]
Is `AIV_PASSGATE` set to `true` when Thorus is bribed? I don't see any problem then.

**Comment by catalinstoian** [comment]
> It is quite tricky to set the variable `thorus_bribed`. It would be easier to check if the AI-variable `AIV_PASSGATE` of `Grd_213_Torwache` is set to true, i.e. the hero is allowed to enter the castle. Do you think it would be enough?

Should look into Diego_GomezAudience = TRUE

**Comment by szapp** [comment]
> 
> 
> > It is quite tricky to set the variable `thorus_bribed`. It would be easier to check if the AI-variable `AIV_PASSGATE` of `Grd_213_Torwache` is set to true, i.e. the hero is allowed to enter the castle. Do you think it would be enough?
> 
> Should look into Diego_GomezAudience = TRUE

Good hint. It looks like this variable has strictly speaking nothing to do with it. In my opinion, the bribe dialog should always remain there until the player is granted access to the castle. This is unambiguously evident by the AI-variable of the guards at the gates. I will update the PR.
