### ISSUE TITLE
Castle gate of the Old Camp cannot close

### ISSUE THREAD

**Issue by szapp** [AmProsius/gothic-1-community-patch#163]
**Describe the bug**
The castle gate of the Old Camp is blocked and cannot close.

**Expected behavior**
The castle gate of the Old Camp is no longer blocked and can properly close.

**Additional context**
The issue arose from a discussion in #124.

1. **Positioning**
The gate is blocked through the wall by the winch (the switch/wheel) that is used to open it. Unfortunately, because of the size and orientation of the bounding boxes the winch has to be moved quite far to avoid collision between the gate and the winch. There are two options:
    1. Either the winch is moved to the opposite wall (see screenshot below)
    2. Or the winch stays where it is and we simply turn off its dynamic collision. That would have the side-effect that the player can walk through it (using it is still possible).

2. **Gate state stored in game save**
Aside from that there is a more pressing issue: The state of the gate is stored in the game save. Once we unblock the gate and it is closed, we will have to revert it to be open on saving the game. The problem here is, that we don't know if the gate was opened during the game due to our fixes (see #124) or by the mod. Therefore, we cannot just revert the gate to *open* on saving, because that might break the mod. Are there any suggestions how we could tackle that problem?

![winch_reposition](https://user-images.githubusercontent.com/20203034/109398767-1a88b700-793f-11eb-8af3-054af7c61ec3.png)

**Comment by pawbuj1981** [comment]
There is similar bug/issue with main gate of Old Camp (close to "OC1" waypoint).  Once gate is being closed/opened again - it looks like can be opened only for 60-70% (like there is obstacle somewhere close).  I have seen it fixed by GMF. 
Also you should think about to add sounds for fixed gates (depens if wood/stone, metal etc.).
