### ISSUE TITLE
Skip gets chapter 2 inventory in chapter 1

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#165]
**Describe the bug**
Skip gets his chapter 2 inventory in chapter 1.

**Expected behavior**
Skip no longer gets his chapter 2 inventory in chapter 1.

**Additional context**
Skip's inventory is also filled in chapter 2:
https://github.com/AmProsius/gothic-1-community-patch/blob/ee528698777a8d7bd67f93b982c5177e6e8ff409/scriptbase/_work/Data/Scripts/Content/Story/Chapters/B_Kapitelwechsel.d#L28-L38

I don't know if this is intentional, so I'll mark this issue as `opinionated`.

**Comment by AmProsius** [comment]
https://github.com/AmProsius/gothic-1-community-patch/blob/ee528698777a8d7bd67f93b982c5177e6e8ff409/scriptbase/_work/Data/Scripts/Content/Story/Chapters/B_Kapitelwechsel.d#L12-L19

changed to

```d
    if      (neues_Kapitel == 1)
    {
        PrintDebugNpc   (PD_MISSION, "---=== DAS ERSTES KAPITEL ===---");

        //IntroduceChapter ("Kapitel 1","Die Welt der Verurteilten","chapter1.tga","levelup.wav", 6000);
        IntroduceChapter ("Chapter 1","Welcome to the colony","chapter1.tga","levelup.wav", 6000);
    }
```

**Comment by szapp** [comment]
I agree with a argument someone had brought up: We don't know this was not intended - as last-minute balance fix. It does not strike me as a mistake.
