### ISSUE TITLE
Jackal doesn't recognize the player's camp membership

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#17]
Jackal still harasses the player for protection money after the player has joined a camp.

**Comment by catalinstoian** [comment]
DIA_GRD_201_Jackal.d

FUNC INT Info_Jackal_Hello_Condition()
{	
	if (Kapitel <= 2) && (Npc_GetTrueGuild(other) == GIL_None)
	{
		return 1;
	};
};
