### ISSUE TITLE
Rice Lord attacks the player

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#170]
**Describe the bug**
After the player defeated Lefty, the Rice Lord attacks him for no reason.

**Expected behavior**
The Rice Lord no longer attacks the player after he defeated Lefty.

**Comment by szapp** [comment]
> ... the Rice Lord attacks him ***for no reason.***

I think that is very much arguable. We don't know if that is not intended. The rice lord is defined as a guard.
https://github.com/AmProsius/gothic-1-community-patch/blob/f386ca443496783307a91437f00772b92802a4dd/scriptbase/_work/Data/Scripts/Content/Story/NPC/BAU_900_Ricelord.d#L1-L6
By definition guards defend their allies if they are attacked. To me personally it never came off as wrong that he would attack me.

**Comment by AmProsius** [comment]
The Rice Lord definitely guards the storage, but he shouldn't guard the people. That's not the way of the New Camp.

**Comment by szapp** [comment]
> The Rice Lord definitely guards the storage, but he shouldn't guard the people. That's not the way of the New Camp.

I disagree, we don't know that. In the game it is often talked about "the rice lord and his thugs" (der Reislord und seine Schläger). They make sure that the farmers are working and not slacking off. After all, the farmers are not rogues that could take care of themselves. The farmers are treated like slaves and are guarded over. It makes sense that the rice lord has interest to also protect them to protect the harvest.

All I see is that the rice lord has the guild "guard". In the scripts that guild is never used/necessary to guard objects or buildings. That's what AI states and portal rooms are for. The guild is exclusively used to guard over other NPCs. To me it seems very much intended that the rice lord guards his people. (From the dialogs of the farmers, the hostility towards the rice lord is very obvious.)

Either way, we don't know that for sure and I think is issue is going way beyond objective bug fixing. This is a very personal assumption and I think it's wrong to base a fix on that. It makes more sense to trust the scripts and give them the benefit of the doubt.

Aside from the conceptual reasons, the guarding behavior in the scripts is only based on camp-membership. Therefore, there is no easy way to exclude the rice lord from interfering when Lefty is attacked. I would just close this issue.
