### ISSUE TITLE
Alcoholic drinks don't have HP value displayed

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#171]
**Describe the bug**
Beer, wine and rice schnapps don't have the amount of HP they heal displayed.

**Expected behavior**
The HP healing value of beer, wine and rice schnapps is now displayed in the inventory.

**Additional context**
These three drinks are the only food related items that don't have their HP healing value displayed. This might have been intentional, so I'll mark this issue as `opinionated` and I'm open for discussion on this matter.

**Comment by AmProsius** [comment]
https://github.com/AmProsius/gothic-1-community-patch/blob/ecc13cadf99a35c7e14059d214220892c2b1677e/scriptbase/_work/Data/Scripts/Content/Items/Food.d#L400

changed to 

```d
    TEXT[1]               = NAME_Bonus_HP;                COUNT[1]    = HP_Bier;
```

---

https://github.com/AmProsius/gothic-1-community-patch/blob/ecc13cadf99a35c7e14059d214220892c2b1677e/scriptbase/_work/Data/Scripts/Content/Items/Food.d#L426

changed to 

```d
    TEXT[1]               = NAME_Bonus_HP;                COUNT[1]    = HP_Wein;
```

---

https://github.com/AmProsius/gothic-1-community-patch/blob/ecc13cadf99a35c7e14059d214220892c2b1677e/scriptbase/_work/Data/Scripts/Content/Items/Food.d#L452

changed to 

```d
    TEXT[1]               = NAME_Bonus_HP;                COUNT[1]    = HP_Reisschnaps;
```

**Comment by szapp** [comment]
I find it suspicious that the values are indeed in the scripts but commented out. That looks like it was on purpose.

**Comment by AmProsius** [comment]
> I find it suspicious that the values are indeed in the scripts but commented out. That looks like it was on purpose.

That's why I added the `opinionated` label. It's merely an inconsistency.

**Comment by szapp** [comment]
Just a heads up: this will be difficult to fix, because new byte code will have to be added where there is no room. It is a bit different from the previous instance variable fixes.

**Comment by AmProsius** [comment]
> The workload of the fix will be a bit unproportional to its effect in my opinion.

I will close it then. It's * opinionated` anyway.
