### ISSUE TITLE
Bloodwyn doesn't recognize the player's camp membership 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#18]
Bloodwyn still harasses the player for protection money after the player has joined a camp.

**Comment by catalinstoian** [comment]
DIA_GRD_233_Bloodwyn.d

FUNC INT Info_Bloodwyn_Hello_Condition()
{	
	if (Kapitel <= 2) && (Npc_GetTrueGuild(other) == GIL_None)
	{
		return 1;
	};
};

**Comment by szapp** [comment]
If someone wants to give it a try, have a look at #17. It's already implemented and this one seems quite similar.

**Comment by Quintus24** [comment]
Hello, everyone,

Sorry for spamming a closed issue, however, just a heads-up, I still encounter this bug.
I joined the **Shadows** and **Guards** guilds, but **Bloodwyn** keeps asking for protection money.
Additionally, if I choose to pay him, the **10 Ore** is not actually deducted and given to him.

I checked the "**fix status 18**" command and it was displayed as being **active**.

Regards,
Quintus24

**Comment by szapp** [comment]
Yes, this issue actually addresses the first dialog of Bloodwyn (first encounter) only, but not the follow up reminders. That is a separate dialog, not part of this fix. I am not sure if there is an issue for that one already.

The fix to reduce 10 ore in that follow up dialog is handled in #109. Could you check that fix's status and report any problems in the respective Github issue?

**Comment by Quintus24** [comment]
Hi, @szapp,

I think I understand now, sorry for the confusion.
I'll double check #109 and report there what I find.

Regards,
Quintus24

**Comment by szapp** [comment]
No worries, it was luckily very easy to double check. Thanks for bringing the faulty follow-up dialog to our attention. I don’t think it is listed as issue so far. Feel free to open an issue for that.
