### ISSUE TITLE
Scorpio's fight dialog doesn't disappear 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#19]
Scorpio can still be asked "Can you teach me to fight?" after he moves to Cavalorn's, since the dialog line to get him to teach the player is another one.

**Comment by catalinstoian** [comment]
DIA_GRD_205_Scorpio.d

FUNC int DIA_Scorpio_REFUSETRAIN_Condition()
{
	if (Npc_KnowsInfo(hero,DIA_Scorpio_Hello) && (Npc_GetTrueGuild (hero) != GIL_GRD) && (Kapitel <= 3) )
	{
		return 1;
	};
};
