### ISSUE TITLE
NPCs don't use doors properly 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#2]
NPCs don't use doors properly.

**Comment by catalinstoian** [comment]
B_MoveMob.d

func void B_MoveMob ()
{	
	var string door; door = Npc_GetDetectedMob(self);
	
	if (Hlp_StrCmp (door, "DOOR"))
	{
		if (Wld_GetMobState (self,door) == 0)
		{
			Npc_ClearAIQueue (self);
		
			AI_UseMob (self, door, 1);
			AI_UseMob (self, door, -1);	//NSC muss sich am Mobsi abmelden, da sonst die Tür wieder zu geht!
		};
	}
	else
	{
		return;
	};	
	AI_ContinueRoutine (self);
};

**Comment by szapp** [comment]
@catalinstoian The differences to the original function are quite big (even when ignoring all the `PrintDebugNpc` calls). Is the usage of `AIV_MOVINGMOB` no longer required? Also `ZS_WaitForPassage` and `PERC_MOVEMOB` seem to be missing.

Can you elaborate how this fix works and why the above mentioned parts are no longer necessary?
