### ISSUE TITLE
Kirgo doesn't give a beer to the player 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#20]
Kirgo doesn't give a beer if the player agrees not to challenge him to a fight in the arena.

**Comment by catalinstoian** [comment]
DIA_GRD_251_Kirgo.d

func void Info_Kirgo_Charge_Beer()
{
	AI_Output (other, self,"Info_Kirgo_Charge_Beer_15_00"); //Okay, give me a beer then!
	AI_Output (self, other,"Info_Kirgo_Charge_Beer_05_01"); //Here you are!
	AI_Output (other, self,"Info_Kirgo_Charge_Beer_15_02"); //Thanks! I'm afraid I can't tell you much about the outside world - they kept me locked away in a dark hole for almost two months before throwing me in here.
	AI_Output (self, other,"Info_Kirgo_Charge_Beer_05_03"); //That's a shame... Oh well, never mind... Hey, you're still looking pretty good for someone who's been locked up for two months.
	AI_Output (other, self,"Info_Kirgo_Charge_Beer_15_04"); //I'd like it to stay that way, too.
	AI_Output (self, other,"Info_Kirgo_Charge_Beer_05_05"); //Then why do you insist on fighting one of us?
	AI_Output (other, self,"Info_Kirgo_Charge_Beer_15_06"); //I want to get acknowledged in the Camp!
	AI_Output (self, other,"Info_Kirgo_Charge_Beer_05_07"); //By Scatty, you mean? Hm, he's one of the most influential men in the Outer Ring... You might be able to impress him by defeating me...
	AI_Output (self, other,"Info_Kirgo_Charge_Beer_05_08"); //But if you really want to impress him, it's Kharim you need to beat. Only thing is, I'm afraid he might be too good for you!
	AI_Output (self, other,"Info_Kirgo_Charge_Beer_05_09"); //If you still want to fight me, let me know! But I won't enjoy knocking you out cold.
	
	CreateInvItem (self, ItFoBeer);
	B_GiveInvItems (self, other, ItFoBeer, 1);
	
	self.npctype = npctype_FRIEND;
	
	Info_ClearChoices	(Info_Kirgo_Charge );
};

**Comment by catalinstoian** [comment]
bonus - German ou translated to English

func VOID Info_Kirgo_InArena_Info()
{
	if (Kapitel <= 1)			//Fix für spätere Kapitel ****Björn****
	{
		AI_Output (self, other,"Info_Kirgo_InArena_05_00"); //Right, let's get to it. May the best man win!
		
		AI_StopProcessInfos	( self );
			
		Npc_ExchangeRoutine(self,"START");
		
		Npc_SetTarget(self,other);
		AI_StartState(self,ZS_ATTACK,1,"");
	}
	else
	{
		AI_Output (self, other,"SVM_5_LetsForgetOurLittleFight"); //Let's forget about that little argument, okay?		
		AI_StopProcessInfos	( self );
		Npc_ExchangeRoutine(self,"START");
	};

};
