### ISSUE TITLE
Version number overlaps mod title

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#202]
**Describe the bug**
There are some mods (the UnPatch mod for example) that use the bottom left corner of the main menu for their title and/or version number. When the G1CP is also installed, its version number overlaps the one from the mod.

**Expected behavior**
The version number of the G1CP no longer overlaps other mods' title and/or version number.

**Additional context**
I will provide a screenshot later.

**Comment by szapp** [comment]
It will be checked if the version info of the G1CP will actually be printed. If so, the mod info print will be disabled.
