### ISSUE TITLE
Fletcher reopens closed quest 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#21]
Fletcher reopens the quest "Vanished Guard" if the quest is already completed.

**Comment by catalinstoian** [comment]
DIA_GRD_255_Fletcher.d

func void  DIA_Fletcher_WoNek_Info()
{
	AI_Output (other, self,"DIA_Fletcher_WoNek_15_00"); //D'you know where Nek's got to?
	AI_Output (self, other,"DIA_Fletcher_WoNek_06_01"); //No, and I'm not likely to find out.
	AI_Output (self, other,"DIA_Fletcher_WoNek_06_02"); //If anything, the diggers in this district might know something. But diggers don't talk to guards.
	AI_Output (self, other,"DIA_Fletcher_WoNek_06_03"); //Especially not now they know I hate this filthy work. I bet they're laughing behind my back!
	
	if (Sly_LostNek != LOG_SUCCESS) && (Npc_GetTrueGuild(hero) == GIL_NONE)
	{
	Log_CreateTopic    (CH1_LostNek, LOG_MISSION);
	Log_SetTopicStatus (CH1_LostNek, LOG_RUNNING);
	};
	B_LogEntry  (CH1_LostNek,"Maybe the diggers in the arena district know where Nek disappeared to.");
};
