### ISSUE TITLE
Y'Berion doesn't attack the player 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#22]
Y'Berion says infinitely "Who let you in?" and doesn't attack the player.

**Comment by catalinstoian** [comment]
DIA_GUR_1200_YBerion.d

FUNC VOID DIA_YBerion_Wache_Info()
{	
	AI_Output			(self,	other,"DIA_YBerion_Wache_12_00"); //What are you doin' here? Who let you in? Guards!
	B_IntruderAlert		(self,	other);
	AI_StopProcessInfos	(self);
	Npc_SetTarget(self,other);
	AI_StartState(self,ZS_ATTACK,1,"");
};

**Comment by szapp** [comment]
Is it not intended that Y'Berion is a peaceful character? Would it be enough to make him stop repeating himself instead of attacking?

**Comment by AmProsius** [comment]
He calls the player "intruder" and calls for the guards. I think it's legit to let him attack. The alternative would be that his guards attack the player.

**Comment by szapp** [comment]
Judging from the original script it might have been intended that the guards come and take care of business, while Y'Berion remains passive. In any case that does not seem to work, because the guards are out of range. I suppose, we can implement him attacking.
