### ISSUE TITLE
Cor Kalom closes wrong quest 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#24]
Cor Kalom closes the "Weed monopoly" quest instead of "Weed delivery".

**Comment by catalinstoian** [comment]
DIA_GUR_1201_CorKalom.d

FUNC VOID Info_Kalom_KrautboteBACK_Info()
{
	AI_Output (other, self,"Mis_1_Psi_Kalom_KrautboteBACK_15_00"); //I've delivered the weed.
	
	if (Npc_HasItems (hero,itminugget)>=500)
	{
		AI_Output (self, other,"Mis_1_Psi_Kalom_KrautboteBACK_10_01"); //Good. Get another task somewhere else.

		Kalom_Krautbote = LOG_SUCCESS;
		B_LogEntry			(CH1_KrautBote,"Cor Kalom received money for the weed delivery to the Ore Barons.");
		Log_SetTopicStatus	(CH1_KrautBote,	LOG_SUCCESS);
		B_GiveInvItems		(hero, self, ItMiNugget, 500);
		B_GiveXP			(XP_WeedShipmentReported);

		Info_Kalom_KrautboteBACK.permanent = 0;
	}
	else
	{
		AI_Output (self, other,"Mis_1_Psi_Kalom_KrautboteBACK_10_02"); //Where's the 500 ore, boy? Make sure I get them real fast!
	}; 
};
