### ISSUE TITLE
Lares's guard doesn't attack the player

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#26]
The rogue guarding Lares hut says infinitely "Go!" but doesn't attack.

**Comment by catalinstoian** [comment]
DIA_ORG_804_Organisator.d

func int Info_Org_804_FirstWarn_Condition()
{
	if (	( (other.guild == GIL_GRD) || (other.guild == GIL_STT) 	) 
	&&	(hero.aivar[AIV_GUARDPASSAGE_STATUS] == AIV_GPS_BEGIN)
	&&	(Npc_GetAttitude(self,hero)	!= ATT_FRIENDLY	) 
	&&		(Hlp_StrCmp(Npc_GetNearestWP(self),self.wp))				)
	{
		return TRUE;
	};
};
