### ISSUE TITLE
The "Warrior's Voice" is described as a "One-handed Weapon".

### ISSUE THREAD

**Issue by Quintus24** [AmProsius/gothic-1-community-patch#282]
Hello, everyone!

I would like to report the following bug:

**Describe the bug:**
The weapon can be found in **Okyl's** inventory in the **Free Mine**.
The "**Warrior's Voice**" weapon is described as a "**One-handed Weapon**", however, it is a **two-handed weapon**.

**Expected behavior:**
The "**Warrior's Voice**" weapon is correctly described as a "**Two-handed Weapon**".

**Steps to reproduce the issue:**
1. Travel to the **Free Mine** and loot NPC "**Okyl**".
2. Open the inventory and notice the weapon's description.

**Additional context**
N/A

_Attaching some screenshots for more clear information_.

1. The "Warrior's Voice".
![Warrior's Voice](https://user-images.githubusercontent.com/93062373/148302581-3ab2873e-fb90-4605-a31e-1a5703102966.JPG)

2. Two-Handed Stance.
![Two-Handed Stance](https://user-images.githubusercontent.com/93062373/148302603-4e97c820-b0db-4a02-aeec-98e259207aa6.JPG)

Thank You and Best Regards!
Quintus24

**Comment by szapp** [comment]
Related to #125. For implementation, see #156.

**Comment by AmProsius** [comment]
The weapon is correctly labelled as a two-handed weapon:
https://github.com/AmProsius/gothic-1-community-patch/blob/2775fbc70322594ed1d00c96717143f0c2af5af7/scriptbase/_work/Data/Scripts/Content/Items/Melee_Weapons.d#L1991-L2014
