### ISSUE TITLE
The "Old Judge" is described as a "One-handed Weapon".

### ISSUE THREAD

**Issue by Quintus24** [AmProsius/gothic-1-community-patch#292]
Hello, everyone!

I would like to report the following bug:

**Describe the bug:**
The weapon can be found in the **Free Mine**, close to the ore smelter.
The "**Old Judge**" weapon is described as a "**One-handed Weapon**", however, it is a **two-handed weapon**.

**Expected behavior:**
The "**Old Judge**" weapon is correctly described as a "**Two-handed Weapon**".

**Steps to reproduce the issue:**
1. Travel to the **Free Mine** and enter it.
2. Find the weapon and pick it up.
3. Open the inventory and notice the weapon's description.

**Additional context**
N/A

_Attaching some screenshots for more clear information_.

1. The "**Old Judge**" weapon.
![Old Judge](https://user-images.githubusercontent.com/93062373/149253072-c164ca6c-6aad-405f-bf93-bae46b79f5dd.JPG)

2. Two-Handed Stance.
![Two-Handed Stance](https://user-images.githubusercontent.com/93062373/149253103-ccbb8cbe-6609-4378-850a-1a744c8293a8.JPG)

Thank You and Best Regards!
Quintus24

**Comment by AmProsius** [comment]
Related to #125. For implementation, see #156.
