### ISSUE TITLE
The "Old Battle Axe" is described as a "One-handed Weapon".

### ISSUE THREAD

**Issue by Quintus24** [AmProsius/gothic-1-community-patch#295]
Hello, everyone!

I would like to report the following bug:

**Describe the bug:**
The weapon can be found on the path to the **Xardas's Tower**.
The "**Old Battle Axe**" weapon is described as a "**One-handed Weapon**", however, it is a two-handed weapon.

**Expected behavior:**
The "**Old Battle Axe**" weapon is correctly described as a "**Two-handed Weapon**".

**Steps to reproduce the issue:**
1. Travel to the **OW_PATH_121** waypoint.
2. Find the weapon and pick it up.
3. Open the inventory and notice the weapon's description.

**Additional context**
N/A

_Attaching some screenshots for more clear information_.

1. The "**Old Battle Axe**".
![Old Battle Axe](https://user-images.githubusercontent.com/93062373/149600039-258d39da-8a2a-4475-986e-4ebf8eeb60c0.JPG)

2. Two-Handed Stance.
![Two-Handed Stance](https://user-images.githubusercontent.com/93062373/149600048-2a8e5ee7-b424-4d80-91a6-f4cb2eee099e.JPG)

3. Location at **OW_PATH_121** waypoint.
![Location @ OW_PATH_121](https://user-images.githubusercontent.com/93062373/149600086-46c5672a-8545-440c-bf21-280023b0e3c1.JPG)

Thank You and Best Regards!
Quintus24

**Comment by AmProsius** [comment]
Related to #125. For implementation, see #156.

**Comment by szapp** [comment]
Much like #298 this may not be the case. See scripts:
https://github.com/AmProsius/gothic-1-community-patch/blob/2892a60a3edf33340d7907fe7b3c137d079e8474/scriptbase/_work/Data/Scripts/Content/Items/Melee_Weapons.d#L1469-L1492
