### ISSUE TITLE
The "Light Two-hander" is described as a "One-handed Weapon".

### ISSUE THREAD

**Issue by Quintus24** [AmProsius/gothic-1-community-patch#298]
Hello, everyone!

I would like to report the following bug:

**Describe the bug:**
The weapon can be purchased from NPC "**Darrion**" in the **Swamp Camp**.
The "**Light Two-hander**" weapon is described as a "**One-handed Weapon**", however, it is a two-handed weapon.

**Expected behavior:**
The "**Light Two-hander**" weapon is correctly described as a "**Two-handed Weapon**".

**Steps to reproduce the issue:**
1. Travel to the **Swamp Camp** and talk with NPC "**Darrion**".
2. Purchase the weapon and open the inventory.
3. Notice the weapon's description.

**Additional context**
N/A

_Attaching screenshots for more clear information_.

1. The "**Light Two-hander**".
![Light Two-hander](https://user-images.githubusercontent.com/93062373/149693888-e0c4c47b-93bb-4ece-b000-b4028a06a820.JPG)

2. Two-Handed Stance.
![Two-Handed Stance](https://user-images.githubusercontent.com/93062373/149694024-7976a9eb-9a9d-4664-a627-eb587a289cfc.JPG)

Thank You and Best Regards!
Quintus24

**Comment by AmProsius** [comment]
Related to #125. For implementation, see #156.

**Comment by AmProsius** [comment]
It seems odd to me that there are so many weapons wrongfully classified. We will have to check that.

**Comment by szapp** [comment]
> It seems odd to me that there are so many weapons wrongfully classified. We will have to check that.

We should check whether these are language dependent.

**Comment by szapp** [comment]
(If I got the right item here,) it is set to the two-handed text.

https://github.com/AmProsius/gothic-1-community-patch/blob/2892a60a3edf33340d7907fe7b3c137d079e8474/scriptbase/_work/Data/Scripts/Content/Items/Melee_Weapons.d#L1552-L1575

There also does not seem to be a problem with the constant.
https://github.com/AmProsius/gothic-1-community-patch/blob/2892a60a3edf33340d7907fe7b3c137d079e8474/scriptbase/_work/Data/Scripts/Content/Story/Text.d#L423-L424

Someone should confirm this issue, because from the look of the scripts, there is no problem.

**Comment by AmProsius** [comment]
I checked `insert ItMw_2H_Sword_Light_01` with a fresh install of Gothic and it was labelled correctly as a *Two-handed weapon*.

@Quintus24 do you play with any other mods/patches?

**Comment by szapp** [comment]
Your exact Gothic version (version number and retail/GOG/Steam/... and script version) may also be interesting to know.

**Comment by AmProsius** [comment]
Mine for example is:
- Installer from GOG
- File version: 1.0.8.11
- Product version: 1.08k_mod

**Comment by Quintus24** [comment]
Hi, guys!

> do you play with any other mods/patches?

I play it on **Steam** and it has the **SystemPack** officially incorporated in it, I can't play the game otherwise due to Access Violation errors and other issues.

> Your exact Gothic version (version number and retail/GOG/Steam/... and script version) may also be interesting to know.

Retail: Steam
Version: 1.08k_mod(SP 1.8)
File Version: 1.0.8.11
Mods: G1CP 1.2

There are weapons that are Two-Handed and have the correct description, I can't remember them from the top of my head, but for example the Pickaxe is correctly labeled as a Two-Handed weapon.

Additionally, all of the Orc weapons are described as One-Handed weapons, however, story wise it makes sense since the Orcs use them as such, but they are too big for the Player Character, therefore, they are used as Two-Handed.

Let me know if I should stop reporting these, in case they are false-positives.

![Version](https://user-images.githubusercontent.com/93062373/149788515-e1973c1c-25fc-440d-8489-76809a425764.JPG)

Best Regards!
Quintus24

**Comment by szapp** [comment]
Would you be willing to go through the trouble to extract the `Gothic.dat` from the file `[Gothic]/Data/Scripts.vdf` (or similar?) with the [GothicVDFS](http://www.bendlins.de/nico/gothic2/) and post it here?

**Comment by Quintus24** [comment]
Hi @szapp 

I tried but I get the "Unexpected VDFS Version!" error, unless I'm doing something wrong on my side.

Regards,
Quintus24

**Comment by szapp** [comment]
@Quintus24 That's very strange. I would like to investigate that to make sure the G1CP covers all sorts of game versions. Is there a way to contact you privately?

**Comment by Quintus24** [comment]
> Is there a way to contact you privately?

Yeah, would a Twitter be ok? Search for @_Quintus24_

**Comment by szapp** [comment]
@Quintus24 Unfortunately, I don't have twitter. Would you be comfortable with uploading your `Scripts.vdf` here? We can delete the comment once I downloaded the file.

**Comment by Quintus24** [comment]
Hi, @szapp,

I'm not sure I know what I'm looking for in those files, if it's ok with you, send me an email here, cihosuf@getnada.com, it's a dummy email I use sometimes.
Then, I can share with you other contact information for more easy communication.

**Comment by AmProsius** [comment]
I just installed the Steam version freshly and I can't reproduce the issue.
