### ISSUE TITLE
NPCs don't collect weapons after fight 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#3]
**Describe the bug**
NPCs don't always collect their weapons and loast ammunition when they regain consciousness after a lost fight.

**Expected behavior**
NPCs now always pick up their weapons and lost ammunition after a lost fight.

**Comment by catalinstoian** [comment]
in B_Functions

func void B_RegainDroppedWeapon(var C_NPC slf)
{
	//-------- fallgelassene Waffe aufheben... --------
	Npc_PerceiveAll (slf);
	if ( Wld_DetectItem (slf, ITEM_KAT_NF) )
	{
		if	!Npc_IsPlayer(slf)
		&&	Npc_CanSeeItem(slf,item)
		&&	!Npc_HasEquippedMeleeWeapon(slf)
		{
			PrintDebugNpc(PD_ZS_CHECK, "...NSC hebt seine Nahkampf-Waffe wieder auf!" );
			AI_TakeItem (slf, item);
			AI_EquipBestMeleeWeapon(slf);
		};
	};
	Npc_PerceiveAll (slf);
	if ( Wld_DetectItem (slf, ITEM_KAT_FF) )
	{
		if	!Npc_IsPlayer(slf)
		&&	Npc_CanSeeItem(slf,item)
		&&	!Npc_HasEquippedRangedWeapon(slf)
		{
			PrintDebugNpc(PD_ZS_CHECK, "...NSC hebt seine Fernkampf-Waffe wieder auf!" );
			AI_TakeItem (slf, item);
			AI_EquipBestRangedWeapon(slf);
		};
	};
	Npc_PerceiveAll (slf);
	if ( Wld_DetectItem (slf, ITEM_KAT_MUN) )
	{
		if	!Npc_IsPlayer(slf)
		&&	Npc_CanSeeItem(slf,item)
		{
			PrintDebugNpc(PD_ZS_CHECK, "...NSC hebt seine Munition wieder auf!" );
			AI_TakeItem (slf, item);
		};
	};
};

**Comment by szapp** [comment]
https://github.com/AmProsius/gothic-1-community-patch/blob/04830dce5c2e03a405100840522ffe53a3750258/src/Ninja/G1CP/Content/Fixes/Session/fix003_RegainDroppedWeapon.d#L32-L70

It seems like a made a mistake with the distances here. 5000 corresponds to 50 meters, which is way too far. Something like 300 as found in the function below seems more reasonable.
https://github.com/AmProsius/gothic-1-community-patch/blob/04830dce5c2e03a405100840522ffe53a3750258/scriptbase/_work/Data/Scripts/Content/AI/B_Human/B_AssessBody.d#L110-L130
