### ISSUE TITLE
Shrike's Hut quest

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#33]
**Describe the bug**
* Gorn can be told about Shrike's defeat even if the player doesn't know about the hut.
* The quest "Shrike's Hut" can't be closed if the player defeats Shrike without knowing from Gorn about the hut.

**Expected behavior**
The quest "Shrike's Hut" can be closed no matter in which order the player gets to know about the quest and defeats Shrike.

**Additional context**
German translation of the quest is *Shrike's Hütte*.

**Comment by catalinstoian** [comment]
(DIA_PC_Fighter.d
```
FUNC int DIA_Gorn_HutFree_Condition()
{
	if (Npc_KnowsInfo(hero,DIA_Gorn_Hut)) && (Npc_KnowsInfo(hero, DIA_Shrike_GetLost))
	{
		return 1;
	};
};

```

**Comment by szapp** [comment]
I will also check whether the quest about Shrike is running (compare to [DIA_Gorn_Hut](../blob/d3c811be3efff371c697ca597f680097e51aa5a7/scriptbase/_work/Data/Scripts/Content/Story/Missions/DIA_PC_Fighter.d#L100-L131)), such that *either* the quest has to be running, or the dialog was told.

```D
FUNC int DIA_Gorn_HutFree_Condition() 
{
    if ((Gorn_ShrikesHut == LOG_RUNNING) || (Npc_KnowsInfo(hero, DIA_Gorn_Hut))) && (Npc_KnowsInfo(hero, DIA_Shrike_GetLost))
	{
		return 1;
	};
};
```
