### ISSUE TITLE
Gorn's HP value is wrong

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#34]
**Describe the bug**
Gorn has 22 HP instead of 220 HP.

**Expected behavior**
Gorn now correctly has 220 HP.

**Additional context**
This bug is not noticeable since Gorn is immortal, but it's a bug nonetheless.

**Comment by AmProsius** [comment]
https://github.com/AmProsius/gothic-1-community-patch/blob/2164a25a66ad4507873dce9cb82146b97476e9b4/scriptbase/_work/Data/Scripts/Content/Story/NPC/PC_Fighter.d#L18-L19

changed to

```D
attribute[ATR_HITPOINTS_MAX]=   220;
attribute[ATR_HITPOINTS]    =   220;
```

**Comment by szapp** [comment]
Strictly speaking this issue should also have the label `opinionated`, because we don’t know what the true health value of Gorn was. Where does the 220 come from?

Given that he is immortal, I don’t see the benefit of this fix.

**Comment by AmProsius** [comment]
> Strictly speaking this issue should also have the label `opinionated`, because we don’t know what the true health value of Gorn was. Where does the 220 come from?
 
Just a guess, the other three friends all have 200+ HP.

> Given that he is immortal, I don’t see the benefit of this fix.

You are right. I will close the issue for now. We can always reopen it we discover any occasion where the HP value matters.
