### ISSUE TITLE
Fisk's quest isn't triggered when Mordrag is dead

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#36]
**Describe the bug**
Fisk's quest "New Fence for Fisk" isn't triggered when Mordrag is dead (either killed by the player or by a monster).

**Expected behavior**
Fisk's quest "New Fence for Fisk" is now also available if Mordrag is dead.

**Comment by catalinstoian** [comment]
DIA_STT_311_Fisk.d

```
FUNC int  Stt_311_Fisk_MordragKO_Condition()
{
	var C_NPC Mordrag; Mordrag = Hlp_GetNpc(Org_826_Mordrag);
	if (Npc_GetTrueGuild(hero) == GIL_NONE) && ( (MordragKO_HauAb == TRUE) || (MordragKO_StayAtNC==TRUE) || (Npc_IsDead(Mordrag)) )
	{
		return 1;
	};
};
```

**Comment by AmProsius** [comment]
As discussed, I want to remove `MordragKO_StayAtNC == TRUE` from the condition, so only `Npc_IsDead(Mordrag)` is added.
