### ISSUE TITLE
Potions have wrong ore value 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#41]
Potion of Velocity and Potion of Haste have the wrong ore value.

**Comment by catalinstoian** [comment]
Potions.d

```
INSTANCE ItFo_Potion_Haste_02(C_Item)
{
	name 			=	NAME_Trank;

	mainflag 		=	ITEM_KAT_POTIONS;
	flags 			=	ITEM_MULTI;

	value 			=	Value_Haste2;	

	visual 			=	"ItFo_Potion_Haste_01.3ds";
	material 		=	MAT_GLAS;
	on_state[0]		=	UseHastePotion2;
	scemeName		=	"POTIONFAST";

	description		= "Potion of Velocity";
	TEXT[1]			= "Allows the player to sprint.";
	TEXT[3]			= NAME_Duration;				COUNT[3]	= Time_Haste2/60000;
	TEXT[5]			= NAME_Value;					COUNT[5]	= value;
};
```

```
INSTANCE ItFo_Potion_Haste_03(C_Item)
{
	name 			=	NAME_Trank;

	mainflag 		=	ITEM_KAT_POTIONS;
	flags 			=	ITEM_MULTI;

	value 			=	Value_Haste3;	

	visual 			=	"ItFo_Potion_Haste_01.3ds";
	material 		=	MAT_GLAS;
	on_state[0]		=	UseHastePotion3;
	scemeName		=	"POTIONFAST";

	description		= "Potion of Haste";
	TEXT[1]			= "Enables the player to sprint longer.";
	TEXT[3]			= NAME_Duration;				COUNT[3]	= Time_Haste3/60000;
	TEXT[5]			= NAME_Value;					COUNT[5]	= value;
};
```

**Comment by szapp** [comment]
Not 100% sure about the labels that I just added (`compatibility easy` and `session fix`). I will have to look up if these properties of items are stored or always initialized from script.

**Comment by szapp** [comment]
> 
> 
> Not 100% sure about the labels that I just added (`compatibility easy` and `session fix`). I will have to look up if these properties of items are stored or always initialized from script. Also refer to #44 #49.

Only the properties `C_Item.amount` and `C_Item.flags` are stored in game saves (aside from the item instance of course). The rest is always initialized from the instance function in the scripts. (Note, however, that the `mainflag` is updated into the `flags` and the flags are saved.)

**Comment by szapp** [comment]
This issue addresses two separate bugs (even if of equal nature) and cannot be confirmed properly if it succeeds for one item but not the other. Therefore, I split it into to separate issues #157 and #158.
