### ISSUE TITLE
Ladder in Old Mine too short 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#53]
The ladder that leads back up from the cave with the cog is too short. It is hard to reach the top without falling down again.

**Comment by szapp** [comment]
Some information on the issue:

1. The nearest waypoint is called OM_185.
2. There are two ladders next to each other that are both not working.
3. The reason for falling down is most likely that the ladders are not vertical but a bit slanted. You can observe this by rotating the camera around the hero while climbing. The hero moves vertically, away from the ladders.

**Comment by AmProsius** [comment]
This issue seems to be fixed with Systempack/Union. No action required anymore.
