### ISSUE TITLE
Ladder in Mountain Fort too short 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#54]
The second ladder in the Mountain Fort is too short. It is hard to reach the top without falling down.

**Comment by szapp** [comment]
I can't reproduce this issue (see video, double speed). I also don't remember from the past that I ever had issues with that particular ladder. Did I try the correct one?

https://user-images.githubusercontent.com/20203034/105900894-f58de500-601c-11eb-8318-4090f14bfb56.mp4

**Comment by AmProsius** [comment]
I can't see the video, but I also can't reproduce the bug (with or without Union). At least I remember the issue. Perhaps it was in the Mountain Fort, not Xardas' Tower. I'll just check that.

**Comment by AmProsius** [comment]
It's indeed the second ladder in the Mountain Fort that's too short. I adjusted the title accordingly.

**Comment by AmProsius** [comment]
Looks like this issue is fixed with Systempack/Union. No action required anymore.
