### ISSUE TITLE
Humanoid monsters don't unequip their weapons after dying

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#6]
Goblins and Skeletons don't have their weapons unequiped when they die.

**Comment by catalinstoian** [comment]
ZS_Dead.d

func void ZS_Dead ()
{	
	PrintDebugNpc	(PD_ZS_FRAME, "ZS_Dead" );		
	PrintGlobals	(PD_ZS_CHECK);

	C_ZSInit();

	self.aivar[AIV_PLUNDERED] = FALSE;
	
	//-------- Erfahrungspunkte für den Spieler ? --------
	//SN: VORSICHT, auch in B_MagicHurtNpc() vorhanden!
	if	Npc_IsPlayer   (other)
	||	(C_NpcIsHuman  (other) && other.aivar[AIV_PARTYMEMBER])
	||	(C_NpcIsMonster(other) && other.aivar[AIV_MM_PARTYMEMBER])
	{
		B_DeathXP();	// vergibt XP an SC
	};
	
	if	C_NpcIsMonster(self)
	{
    if((self.guild == GIL_GOBBO) || (self.guild == GIL_SKELETON))
		{ 
      Npc_SetToFistMode(self);
    };
		B_GiveDeathInv (); 	// für Monster
	};
    B_CheckDeadMissionNPCs ();
    B_Respawn (self); 	
    AI_UnequipWeapons (self);
};

**Comment by szapp** [comment]
catalinstoian's code only seems to target goblins and skeletons. @AmProsius, could you elaborate under what conditions that also happens to other NPCs (and which ones)?

**Comment by catalinstoian** [comment]
> catalinstoian's code only seems to target goblins and skeletons. @AmProsius, could you elaborate under what conditions that also happens to other NPCs (and which ones)?

Yes, code is intended only for those specific monsters. No idea why I said NPCs...

**Comment by AmProsius** [comment]
I changed the title to better reflect the actual issue.

**Comment by szapp** [comment]
@AmProsius can you elaborate on the actual bug here? I was gonna fix it, but I cannot even reproduce the issue. Skeletons and goblins drop their weapons on the ground when they die. Can you confirm I understand correctly by trying test 6, see #73?

**Comment by szapp** [comment]
![test006](https://user-images.githubusercontent.com/20203034/105076567-813acb00-5a8b-11eb-8716-d14d7f4a2a8c.png)

**Comment by AmProsius** [comment]
I can't reproduce the issue with SystemPack or with Union.

Unfortunately I can't test it without either of those because the game keeps crashing:

![access_violation](https://user-images.githubusercontent.com/2817152/105102163-1ef3c180-5aaf-11eb-8bda-9b74380f1ce9.jpg)

**Comment by AmProsius** [comment]
Closed as this bug can't be reproduced.

**Comment by pawbuj1981** [comment]
newest SP or Union (I don't remember which is proper ) fixed it !
