### ISSUE TITLE
Multiply Raw Steel in inventory at smithy 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#63]
The player can multiply Raw Steel in his inventory with the following method: On each of the four steps of smithing (i.e. forge, anvil, water bucket and grindstone) you can fast click Arrow Up and Arrow Down as to process multiple items in a row. After every step, you will find more Raw Steel (or a processed variant) in your inventory. After all four steps, you have roughly 25% more Raw Steel than before (depends on the amount of Raw Steel you processed overall).

**Comment by catalinstoian** [comment]
This involves editing Humans.mds or corresponding anis. In Humans.mds raw steel is attached to hand slot.

(same story with raw meat or destroying lab flash when interacting with laboratory)

**Comment by szapp** [comment]
> (same story with raw meat or destroying lab flash when interacting with laboratory)

But raw meat will not be multiplied will it? The process of cooking the meat is just sped up (i.e. raw meat replaced by cooked meat immediately), or am I mistaken?

**Comment by AmProsius** [comment]
This issue seems to be fixed by Systempack/Union. No action required anymore.
