### ISSUE TITLE
NPCs practice sword training without a weapon

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#7]
NPCs practice sword training without a weapon when they were defeated in a fight before.

**Comment by catalinstoian** [comment]
ZS_PracticeSword.d

func void ZS_PracticeSword_Loop()
{	
    PrintDebugNpc		(PD_TA_LOOP,	"ZS_PracticeSword_Loop");

	if !Npc_HasReadiedMeleeWeapon(self) // ohne Waffe siehts doof aus
	{
		//AI_StartState( self, ZS_StandAround, 1, "" );
		AI_ReadyMeleeWeapon	(self);
	};

	AI_PlayAni			(self,"T_1HSFREE");
	AI_GotoWP			(self, self.wp); 
	AI_AlignToWP    	(self);
};
