### ISSUE TITLE
NPCs move in circles 

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#8]
NPCs are stuck or move in circles when trying to align if another NPC is standing on their spot.

**Comment by catalinstoian** [comment]
ZS_StandAround.d

func int ZS_StandAround_Loop ()
{
	PrintDebugNpc			(PD_TA_LOOP,	"ZS_StandAround_Loop");
	
	//-------- Feinpositionierung abhängig von Vorgängerzustand! --------
	if Npc_WasInState(self,ZS_Smalltalk)
	{
	    B_GotoFP				(self,	"SMALLTALK");
	    AI_AlignToFP( self );				//Richte Dich aus
	}
	else
	{
		if (Wld_IsFPAvailable (self,"CAMPFIRE"))
		{
			if (!Npc_IsOnFP(self, "CAMPFIRE"))
			{
				B_GotoFP (self,	"CAMPFIRE");
				AI_AlignToFP( self );
			};
		}
		else
		{
			Npc_PerceiveAll (self);
			if (Wld_DetectNpcEx(self, -1, NOFUNC, -1, 0)) //other = Nearest Npc (0=Spieler ignorieren!)
			{
				if (!Npc_CanSeeNpc(self, other))
				{
					AI_TurnToNpc (self,other);
				};
			};
		};	};   

    //-------- Suche nach Smalltalk-Partner ! --------
    if Npc_WasInState(self,ZS_Smalltalk)
	{
	    Npc_SendPassivePerc		(self,	PERC_NPCCOMMAND,	self,	self);
	};

**Comment by szapp** [comment]
Can someone supply circumstances in which that bug happens (e.g. a spot/NPC/time in the world where I can observe it)?

**Comment by szapp** [comment]
> Some background info. As I understand the issue is the following. Some actions of daily routine's require a so called freepoint. A freepoint is somewhat like a waypoint but for a specific action. For example, to have two NPCs in the smalltalk-state to face each other, or to have an NPC position themselves in front of the campfire when operating the scavenger bbq. A freepoint can only be used by one NPC at a time, hence a freepoint can either be free or occupied. I haven't really understood the underlying problem of the bug and also not the provided fix completely. From the code it looks like it prevents NPCs from repeatedly repositioning (aligning) themselves on the freepoint they are already standing on. (So strictly speaking it should have nothing to do with other NPCs blocking their way?!)

**Comment by szapp** [comment]
This issue has to be revisited. The described problem is different from the provided fix.

**Comment by szapp** [comment]
I will close this issue until we have more information on it.
