### ISSUE TITLE
Missing armor values for High Robes

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#80]
The High Robe of Fire and the High Robe of Water lack their armor values.

**Comment by AmProsius** [comment]
https://github.com/AmProsius/gothic-1-community-patch/blob/e66b303623c042ec5cfc387a1b0d4bd352605f12/scriptbase/_work/Data/Scripts/Content/Story/Text.d#L585-L586

changed to

```D
const string NAME_CorristoHighRobe	= 	"High Robe of Fire. Protection: Weapons 50, Arrows 5, Fire 30, Magic 10";
const string NAME_SaturasHighRobe	= 	"High Robe. Protection: Weapons 70, Arrows 10, Fire 45, Magic 20";
```

**Comment by szapp** [comment]
This fix will be a bit more elaborate for compatibility with extension mods that might have tweaked the armor values. Instead of giving a fixed string, I want to obtain the values from the armor item. If the item cannot be found (due to it being renamed), the string would remain untouched.

**Comment by szapp** [comment]
The fix would actually be quite easy (also compatibility wise) much like #43. But because of what I wrote above I marked it as difficult.

**Comment by szapp** [comment]
Do we know how this looks for other languages?

**Comment by szapp** [comment]
DE
```D
const string NAME_CorristoHighRobe	= 	"Meister, ich möchte die hohe Robe des Feuers tragen.";
const string NAME_SaturasHighRobe	= 	"Hohe Robe";
```

PL
```D
const string NAME_CorristoHighRobe = "Mistrzu, chciałbym nosić szatę Arcymaga Ognia.";
const string NAME_SaturasHighRobe = "Szata Arcymaga";
```

RU
```D
const string NAME_CorristoHighRobe = "Господин мой, я хочу носить облачение высших магов Огня.";
const string NAME_SaturasHighRobe = "Облачение высших магов";
```

**Comment by AmProsius** [comment]
The way I see it, this issue is not a bug but merely an inconsistency. Therefor I added the `opinionated` label.

**Comment by szapp** [comment]
I agree. In comparison: #125 is truly language independent, because the strings for two handed and one handed are inferred from the constants - the fix thus works with any language. Here, we cannot do that and we can only fix this for specified strings with exact wording. Quite tricky.

**Comment by szapp** [comment]
Actually, I am now inclined to close this issue. I thought the string could be build form existing parts. But the protection descriptions do not match:
https://github.com/AmProsius/gothic-1-community-patch/blob/3a05e2b8be5363bf39c7ef26637838e6d6673312/scriptbase/_work/Data/Scripts/Content/Story/Text.d#L409-L412
https://github.com/AmProsius/gothic-1-community-patch/blob/3a05e2b8be5363bf39c7ef26637838e6d6673312/scriptbase/_work/Data/Scripts/Content/Story/Text.d#L587

Therefore, it is not possible to "automate" that string in any language and ensure that it will look like the other armor strings. In the end it may be just as inconsistent as it is now.
