### ISSUE TITLE
The player doesn't fall when in walking mode

### ISSUE THREAD

**Issue by AmProsius** [AmProsius/gothic-1-community-patch#89]
**Describe the bug**
When in walking mode, the player doesn't fall from cliffs/slopes.

**Expected behavior**
When in walking mode, the player falls from cliffs/slopes like when in running mode.

**Comment by szapp** [comment]
If I remember correctly, this is not a bug, but a feature. It serves to allow the player to get as close to - what the engine calls - chasms as possible without falling.

**Comment by AmProsius** [comment]
I understand. So *it's not a bug, it's a feature*.
